name: Hello
on: push
jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            # リテラルブロック。改行を維持したまま一つの文字列としてrunに渡す。各行がそのまま実行される。
            - run: |
                echo "hello, world"
                tree | cat
                ls
            - uses: actions/checkout@v7
              with: # どのブランチをチェックアウトするか。省略したら、コミットされたbranchになる。
                ref: main
            - run: |
                ls
                whoami
                tree
                python --version
            - uses: actions/checkout@v7
            - run: >
                ls
            - uses: actions/setup-python@v7
              with:
                python-version: "3.15"
            - run: |
                python --version
                python main.py
    goodby:
        name: goodbyの表示名。goodbyはid扱いでこっちが表示用
        needs: hello
        if: success(0)
        timeout-minutes: 30
        runs-on: ubuntu-latest
        steps:
            # jobが分かれているので、この段階ではcheckoutされておらず
            # main.pyとかもなくてエラーになる

            # GitHub Actionsの run は通常、
            # コマンドがゼロ以外の終了コードを返すと、その時点でステップを失敗させます。
            # 失敗すると同じジョブの後続ステップも通常はスキップされます。
            - run: |
                python --version
                python main.py
                python --version
            # これはスキップされて実行されない
            - uses: actions/checkout@v7

