name: Hello
on: push
jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            # リテラルブロック。改行を維持したまま一つの文字列としてrunに渡す。各行がそのまま実行される。
            - run: |
                echo "hello, world"
                tree | cat
                ls
            - uses: actions/checkout@v7
              with: # どのブランチをチェックアウトするか。省略したら、コミットされたbranchになる。
                ref: main
            - run: |
                ls
                whoami
                tree
            - uses: actions/checkout@v7
            - run: >
                ls
